### ISSUE TITLE
keydown not working on IE11 and Chrome

### ISSUE THREAD

**Issue by kenwu27** [HackedByChinese/ng-idle#97] opened 2015-07-15 06:07 UTC
Hi,
I added ngIdle to my application, all worked fine except keydown. I added keypress in angular-idle.js and now it is detecting when I am typing with keyboard. Good thing is mousemove and mousedown always work for me on both browsers unlike what have been reported by others. Thanks for the great work!

**Comment by HackedByChinese** [comment] 2015-11-07 19:49
I don't seem to be having the same issue. Might have been caused by one of the other issues closed in 1.1.1. Try it again with the new release and see how it goes.

**Closed by HackedByChinese** 2015-11-07 19:49 UTC
