### ISSUE TITLE
Triggering digest cycles on mouseMove/scroll/click/...

### ISSUE THREAD

**Issue by schinken** [HackedByChinese/ng-idle#53] opened 2015-03-08 12:07 UTC
I'm using ng-idle on my tool "strichliste" (Demo here: http://demo.hackerspace-bootstrap.org/strichliste-web/). I'm rendering the index page with the following html snippet:

```html
<li ng-repeat="user in users | filter:isActiveUser | orderBy:'name'" ng-click="userClick(user.id)" class="col-xs-2 panel panel-default" title="{{user.name}}">
    <div class="name">{{user.name}}</div>
    <div class="balance" ng-class="user.balance < 0 ? 'negative' : ''">{{user.balance | number:2}} {{currency}}</div>
</li>
```

My filter looks like this:

```javascript
$scope.isActiveUser = function() {
 // some code
};
```

I added some console.log for debug purpose to this function and figures out, that on every mouse move, click or scroll (maybe more events) the filter again is triggered for each entry.

ng-idle is configured like this:
``` javascript

if(settings.idleTimeout) {
    app
        .config(function($idleProvider) {
            $idleProvider.idleDuration(Math.ceil(settings.idleTimeout/1000));
            $idleProvider.warningDuration(1);
        })
        .run(function($rootScope, $idle, $location, locationService) {

            $idle.watch();

            $rootScope.$on('$idleTimeout', function() {
                if($location.path() != '/') {
                    locationService.gotoHome();
                }
            });

        });
}
```

If I comment $idle.watch(), the "problem" is gone, but the timeout doesn't work anymore - of course ;)
Is this intended behaviour? I think this reduces the performance of my angular app a lot

**Comment by HackedByChinese** [comment] 2015-03-10 04:55
What version are you using? See #18

**Comment by schinken** [comment] 2015-03-10 07:27
~0.3.5

**Comment by schinken** [comment] 2015-03-10 08:15
As far as i can see, the problem still persists with 0.3.4 and angular 1.3.14.

**Comment by PSDCoder** [comment] 2015-03-10 09:04
Hi. I have the same problem. Version of ng-idle: 0.3.5, angular - 1.3.14

**Comment by PSDCoder** [comment] 2015-03-10 09:24
I think it's because you are using $interval service, which by default will trigger $digest cycle. [Demo](http://jsbin.com/jijola/1/edit?html,js,console,output) 
But we can change behavior of $interval if pass 4th parameter "invokeApply" https://code.angularjs.org/1.3.14/docs/api/ngMock/service/$interval

**Comment by HackedByChinese** [comment] 2015-03-10 15:24
I think the conclusion is that 0.3.4 is the solution if you're stuck on AngularJS _1.2_.

The issue is resolved in 1.0.0, but it's not officially released yet. I've been trying to wrap that up for months now but personal matters have interceded. As an interim, you can try using angular-idle.js/.min.js right from the develop branch.

**Closed** 2015-03-19 20:56 UTC

**Comment by schinken** [comment] 2015-05-05 08:58
Updated ng-idle to 1.0.4. The configuration now looks like this (migrating from 0.3.5)

```js
    app
        .config(function(IdleProvider) {
            IdleProvider.idle(Math.ceil(settings.idleTimeout/1000));
            IdleProvider.timeout(false);
        })
        .run(function($rootScope, Idle, $location, locationService) {

            Idle.watch();

            $rootScope.$on('IdleStart', function() {
                console.log("IdleStart");

                if($location.path() != '/') {
                    locationService.gotoHome();
                }
            });

        });
```

The digest cycle explained in the first post is still triggerd. Am im using it wrong? Btw, Im still using angular 1.2.21

**Comment by schinken** [comment] 2015-05-05 09:17
Btw, it works with angular 1.3.15

**Comment by HackedByChinese** [comment] 2015-05-06 15:09
Please see this comment from #18: https://github.com/HackedByChinese/ng-idle/issues/18#issuecomment-64758051
